import { z } from 'zod';

/**
 * Presentation content, extracted from the same source as everything else.
 *
 * The map of Türkiye, the guides' greetings and the category badges are
 * authored content, not decoration. They were rebuilt by hand once and came out
 * wrong; they are now generated by `scripts/build-presentation.mjs`.
 */
export const presentationSchema = z.object({
  schemaVersion: z.literal('1.0'),
  contentAuthority: z.literal('index-html-canonical'),
  source: z.object({ file: z.string(), sha256: z.string().length(64) }),
  map: z.object({
    viewBox: z.string(),
    landPaths: z.array(z.string().min(200)).min(1),
  }),
  guides: z.record(z.string(), z.object({ name: z.string(), greeting: z.string() })),
  city: z.object({
    welcomeTitle: z.string(),
    welcomeBody: z.string(),
    startButton: z.string(),
  }),
  categories: z.record(z.string(), z.object({ label: z.string(), color: z.string() })),
});

export type Presentation = z.infer<typeof presentationSchema>;

/** Fills `{name}`, `{city}` and `{stopCount}` in an extracted template. */
export function fillTemplate(
  template: string,
  values: Readonly<Record<string, string | number>>,
): string {
  return template.replace(/\{(\w+)\}/g, (whole, key: string) =>
    key in values ? String(values[key]) : whole,
  );
}
