import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = path.resolve(process.cwd(), '..');

/**
 * The root `content/` tree is the only editable source; `public/content` is
 * generated by `npm run content:sync`. This test fails the moment the two
 * drift, which is what stopped the İstanbul quiz change from living in only
 * one of them (Gate A: content source-of-truth safeguard).
 */
describe('content source of truth', () => {
  it('has no drift between root content and the served copies', () => {
    expect(() =>
      execFileSync('node', ['scripts/sync-content.mjs', '--check'], { stdio: 'pipe' }),
    ).not.toThrow();
  });

  it('serves byte-identical city files', () => {
    for (const cityId of ['istanbul', 'nevsehir', 'gaziantep']) {
      const source = readFileSync(path.join(ROOT, `content/pilot/${cityId}.json`), 'utf8');
      const served = readFileSync(path.resolve(`public/content/pilot/${cityId}.json`), 'utf8');
      expect(served, cityId).toBe(source);
    }
  });

  it('detects drift when a served copy is edited', () => {
    const served = path.resolve('public/content/regions.json');
    const original = readFileSync(served, 'utf8');
    try {
      writeFileSync(served, original.replace('Marmara', 'Marmaraa'));
      expect(() =>
        execFileSync('node', ['scripts/sync-content.mjs', '--check'], { stdio: 'pipe' }),
      ).toThrow();
    } finally {
      writeFileSync(served, original);
    }
  });
});
