import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = path.resolve(process.cwd(), '..');

/**
 * The root `content/` tree is the only editable source; `public/content` is
 * generated by `npm run content:sync`. This test fails the moment the two
 * drift, which is what stopped the İstanbul quiz change from living in only
 * one of them (Gate A: content source-of-truth safeguard).
 */
describe('content source of truth', () => {
  it('has no drift between root content and the served copies', () => {
    expect(() =>
      execFileSync('node', ['scripts/sync-content.mjs', '--check'], { stdio: 'pipe' }),
    ).not.toThrow();
  });

  it('serves byte-identical canonical and scene files', () => {
    for (const cityId of ['istanbul', 'nevsehir', 'gaziantep']) {
      for (const [source, served] of [
        [`content/canonical/cities/${cityId}.json`, `public/content/canonical/cities/${cityId}.json`],
        [`content/scenes/${cityId}.json`, `public/content/scenes/${cityId}.json`],
      ] as const) {
        expect(readFileSync(path.resolve(served), 'utf8'), served).toBe(
          readFileSync(path.join(ROOT, source), 'utf8'),
        );
      }
    }
  });

  it('never publishes the 366 KB combined canonical file to the browser', () => {
    expect(existsSync(path.resolve('public/content/canonical/cities.all.json'))).toBe(false);
  });

  it('detects drift when a served copy is edited', () => {
    const served = path.resolve('public/content/canonical/regions.json');
    const original = readFileSync(served, 'utf8');
    try {
      writeFileSync(served, original.replace('Marmara', 'Marmaraa'));
      expect(() =>
        execFileSync('node', ['scripts/sync-content.mjs', '--check'], { stdio: 'pipe' }),
      ).toThrow();
    } finally {
      writeFileSync(served, original);
    }
  });
});
